main/auth.py
from flask import Blueprint, request, redirect, url_for, render_template, flash, session, jsonify, current_app
import flask_login
import bcrypt
import datetime
from model.model_platform import User, UserProfiles, UserRoles, Roles, Permissions, db, Session
from model.google import init_google_oauth
from config import Config
from .routine_schedule import schedule_notifications

auth = Blueprint('auth', __name__)
google = init_google_oauth(Config.GOOGLE_OAUTH2_CLIENT_ID, Config.GOOGLE_OAUTH2_CLIENT_SECRET)

# 로그인
@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        id = request.form.get("id")
        password = request.form.get("password")
        user = User.query.filter_by(ID=id).first()

        if user and bcrypt.checkpw(password.encode('utf-8'), user.Password.encode('utf-8')):
            flask_login.login_user(user)
            try:
                with current_app.app_context():
                    schedule_notifications()
            except Exception as e:
                print(f"Error scheduling notifications: {e}")

            if user.is_admin():
                return jsonify({"success": True, "redirect": url_for("views.dashboard_page")})
            else:
                return jsonify({"success": True, "redirect": url_for("views.home")})
        else:
            return jsonify({"success": False, "message": "로그인에 실패했습니다. 아이디와 비밀번호를 확인해주세요."})
        
    user_agent = request.user_agent.string
    if "Mobi" in user_agent:
        print('mobile')
        return redirect(url_for("auth.m_login")) 
    else:
        return render_template('Platform/login.html')

@auth.route('/m.login', methods=['GET', 'POST'])
def m_login():
    user_agent = request.user_agent.string
    if "Mobi" in user_agent:
        print('mobile')
        return render_template('Platform/m_login.html')
    else:
        return redirect(url_for("auth.login")) 
    

# 구글 로그인
@auth.route("/google/login")
def google_login():
    return google.authorize(callback=url_for('auth.google_callback', _external=True))

@auth.route('/google/callback')
def google_callback():
    resp = google.authorized_response()
    if resp is None or resp.get('access_token') is None:
        return 'Access denied: reason=%s error=%s' % (
            request.args['error_reason'],
            request.args['error_description']
        )
    
    session['google_token'] = (resp['access_token'], '')
    user_info = google.get('userinfo').data

    email = user_info['email']
    name = user_info.get('name', '')

    session_db = Session()
    user = session_db.query(User).filter_by(Email=email).first()

    if user is None:
        new_user = User(
            ID=email,  
            Username=name,
            Password='', 
            Email=email,
            Phone='',
            DateOfBirth=None,
            DateJoined=datetime.datetime.now(),
            Status='active'
        )
        session_db.add(new_user)
        session_db.commit()

        new_user_profile = UserProfiles(
            UserID=new_user.UserID,
            ID=email,
            Username=name,
            FirstName='새로운',
            LastName='뉴비',
            Address=''
        )
        session_db.add(new_user_profile)
        session_db.commit()

        default_role = session_db.query(Roles).filter_by(RoleName='Basic User').first()
        default_permission = session_db.query(Permissions).filter_by(PermissionName='User').first()

        new_user_role = UserRoles(
            UserID=new_user.UserID,
            RoleID=default_role.RoleID,
            PermissionID=default_permission.PermissionID
        )
        session_db.add(new_user_role)
        session_db.commit()

        user = new_user

    flask_login.login_user(user)
    return redirect(url_for('views.home'))

@google.tokengetter
def get_google_oauth_token():
    return session.get('google_token')

def remove_fcm_token():
    user_id = flask_login.current_user.UserID
    user = User.query.get(user_id)
    if user:
        user.FCMToken = None
        db.session.commit()
        return jsonify({"message": "Token removed successfully"}), 200
    return jsonify({"error": "User not found"}), 404
# 로그아웃
@auth.route("/logout")
def logout():
    remove_fcm_token()
    flask_login.logout_user()
    return redirect(url_for('auth.login'))

# 회원가입
@auth.route('/register', methods=['POST'])
def register():
    name = request.form.get('name')
    join_id = request.form.get('join_id')
    join_pwd = request.form.get('join_pwd')
    # birth = request.form.get('birth')
    phone = request.form.get('phone')
    email = request.form.get('email')
    # address = request.form.get('address')
    # address2 = request.form.get('address2')
    # address3 = request.form.get('address3')

    print(f"join_id: {join_id}")
    hashed_pwd = bcrypt.hashpw(join_pwd.encode('utf-8'), bcrypt.gensalt())
    # full_address = f"{address}, {address2}, {address3}"
    
    session_db = Session()
    
    new_user = User(
        ID=join_id,
        Username=name,
        Password=hashed_pwd,
        Email=email,
        Phone=phone,
        # DateOfBirth=birth,
        DateJoined= datetime.datetime.now(),
        Status='active'
    )
    session_db.add(new_user)
    session_db.commit()

    new_user_profile = UserProfiles(
        UserID=new_user.UserID, 
        ID=join_id, 
        Username=name,
        FirstName="새로운",
        LastName="뉴비",
        # Address=full_address
    )
    db.session.add(new_user_profile)
    db.session.commit()

    default_role = session_db.query(Roles).filter_by(RoleName='Basic User').first()
    default_permission = session_db.query(Permissions).filter_by(PermissionName='User').first()

    new_user_role = UserRoles(
        UserID=new_user.UserID,
        RoleID=default_role.RoleID,
        PermissionID=default_permission.PermissionID
    )
    session_db.add(new_user_role)
    session_db.commit()
    session_db.close()

    flash('Account created successfully!', 'success')
    return redirect(url_for('auth.login'))

# 아이디 중복 확인
@auth.route('/check_id', methods=['GET'])
def check_id():
    join_id = request.args.get('join_id')
    user = User.query.filter_by(ID=join_id).first()
    return jsonify({'exists': user is not None})

# 개인정보 동의 문서 읽어오기
@auth.route('/get_terms_of_use')
def get_terms_of_use():
    with open('static/src/TermsofUse/TermsofUse.txt', 'r', encoding='utf-8') as file:
        terms_of_use = file.read()
    return terms_of_use

@auth.route('/get_personal_information')
def get_personal_information():
    with open('static/src/TermsofUse/PersonalInformation.txt', 'r', encoding='utf-8') as file:
        personal_information = file.read()
    return personal_information

main/views.py
from flask import Blueprint, jsonify, render_template, redirect, url_for, request
from flask_login import current_user, login_required
from model.model_platform import ServiceUsage
import base64

views_bp = Blueprint('views', __name__)

@views_bp.route('/')
def home():
    if current_user.is_authenticated:
        user_profile = current_user.user_profile[0]
        profile_picture = user_profile.ProfilePicture
        encoded_profile_picture = None
        if profile_picture:
            encoded_profile_picture = base64.b64encode(profile_picture).decode('utf-8')
        
        if(current_user.is_admin()):
            return render_template('Platform/Dashboard.html', encoded_profile_picture=encoded_profile_picture, is_admin=current_user.is_admin())
        elif(not current_user.is_admin()):
            return render_template('Platform/home.html', encoded_profile_picture=encoded_profile_picture, is_admin=current_user.is_admin())
    else:
        return redirect(url_for('auth.login'))

@views_bp.route('/account')
def account():
    if current_user.is_authenticated:
        user_profile = current_user.user_profile[0]
        profile_picture = user_profile.ProfilePicture
        encoded_profile_picture = None
        if profile_picture:
            encoded_profile_picture = base64.b64encode(profile_picture).decode('utf-8')

        recent_usage = ServiceUsage.query.filter_by(UserID=current_user.UserID).order_by(ServiceUsage.UsageDate.desc()).first()
        recent_usage_date = recent_usage.UsageDate if recent_usage else None

        return render_template('Platform/account.html', encoded_profile_picture=encoded_profile_picture, latestUsageDate=recent_usage_date, is_admin=current_user.is_admin())
    else:
        return redirect(url_for('auth.login'))

@views_bp.route('/error')
def error():
    return render_template('Platform/error.html')

@views_bp.route('/donotdisturb')
def donotdisturb():
    return render_template('Platform/donotdisturb.html')

@views_bp.route('/introdeveloper')
def introdeveloper():
    return render_template('Platform/introdeveloper.html')

@views_bp.route('/introservice')
def introservice():
    return render_template('Platform/introservice.html')

@views_bp.route('/Dashboard')
def dashboard_page():
    return render_template('Platform/dashboard.html', is_admin=current_user.is_admin())

@views_bp.route('/routine')
def loading():
    return render_template('SmartRoutine/loading.html')

@views_bp.route('/check-login-status') # 로딩 페이지 - 로그인 확인
def check_login_status():
    if current_user.is_authenticated:
        return jsonify({"isLoggedIn": True})
    else:
        return jsonify({"isLoggedIn": False})

@views_bp.route('/routine-home')
@login_required
def routine():
    return render_template('SmartRoutine/routine.html')

@views_bp.route('/routine_notice')
def routine_setting():
    return render_template('SmartRoutine/routine_notice.html')

@views_bp.route('/redirect-to-webapp')
def redirect_to_webapp():
    if current_user.is_authenticated:
        return redirect(url_for('views.routine'))  # 로그인된 경우 app으로 리다이렉트
    else:
        return redirect(url_for('auth.login'))  # 로그인되지 않은 경우 로그인 페이지로 리다이렉트
    
@views_bp.route('/control_home')
def control_home():
    return render_template('SmartRoutine/control_home.html')

@views_bp.route('/notification')
def notification():
    return render_template('SmartRoutine/routine_notice.html')

templates/layouts/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SmartPlatform Footer</title>

    <style>
        body {
            margin: 0;
            display: flex;
            min-height: 100vh;
            flex-direction: column;
        }

        footer {
            background-color: #131419;
            text-align: center;
            color : #6c757d;
            font-weight: 300;
            font-style: normal;
            padding: 10px;
            position: fixed;
            bottom: 0;
            width: 100%;
        }
    </style>
</head>
<body>    
    <footer>
        <p>2024 @ made by 방해금지모드</p>
    </footer>
</body>
</html>

templates/layouts/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}SmartPlatform Header with Mobile Navigation Bar{% endblock %}</title>

    <!-- IONICONS -->
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            background-color: #131419 !important;
            color: #131419;
            display: flex;
            flex-direction: column;
            min-height: 100vh;
            width: 100%;
        }

        .header {
            width: 100%;
            background-color: #131419;
            padding: 20px 0px;
            box-shadow: -5px -5px 10px rgba(255, 255, 255, 0.05), 5px 5px 15px rgba(0, 0, 0, 0.5);
            position: fixed;
            top: 0;
            left: 0;
            display: flex;
            justify-content: center;
            z-index: 1000;
        }

        .logo {
            display: flex;
            align-items: center;
        }

        .content {
            margin-top: 100px;
            width: 100%;
            display: flex;
            flex-direction: column;
            align-items: center;
            flex: 1;
            padding-bottom: 30px;
        }

        .navbar_1 {
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
            background-color: #131419;
            display: flex;
            justify-content: space-around;
            align-items: center;
            height: 60px;
            box-shadow: -5px -5px 10px rgba(255, 255, 255, 0.05), 5px 5px 15px rgba(0, 0, 0, 0.5);
            z-index: 1000;
            transition: width 0.3s ease;
        }

        .nav-item {
            text-decoration: none;
            color: #fff;
            font-size: 16px;
            text-transform: uppercase;
            transition: color 0.3s ease, width 0.3s ease, padding-left 0.3s ease;
            padding: 10px; 
            display: flex;
            align-items: center;
            position: relative;
            overflow: hidden;
        }

        .nav-item .nav__icon {
            font-size: 20px; 
            transition: margin-left 0.3s ease;
        }

        .nav-item span {
            display: none;
            margin-left: 8px;
            white-space: nowrap;
        }

        .nav-item.active .nav__icon,  
        .nav-item.active .span {
            color: #96C9F4;
        }

        .navbar_1.expanded .nav-item {
            width: 150px;
        }

        .navbar_1.expanded .nav-item .nav__icon {
            margin-left: 10px;
        }

        .nav-item:hover {
            color: #96C9F4;
            transform: translateX(15px);
        }

        @media (min-width: 768px) {
            .navbar_1 {
                position: fixed;
                bottom: 0;
                left: 0;
                width: 60px;
                height: 100%;
                flex-direction: column;
                justify-content: center;
                z-index: 999;
                transition: width 0.3s ease;
            }

            .nav-item {
                padding: 20px 10px 20px 50px; 
                width: 60px;
            }

            .navbar_1.expanded {
                width: 200px;
            }

            .navbar_1.expanded .nav-item {
                width: 100%;
            }

            .navbar_1.expanded .nav-item .nav__icon {
                margin-left: 10px; 
            }

            .navbar_1.expanded .nav-item span {
                display: inline-block;
            }
        }

        footer {
            background-color: #131419;
            text-align: center;
            color: #6c757d;
            font-weight: 300;
            font-style: normal;
            padding: 10px;
            width: 100%;
            position: fixed; /* fixed에서 relative로 변경 */
            margin-bottom: 100px;
        }
    </style>
    {% block styles %}{% endblock %}
</head>
<body>
    <!-- Header -->
    <header class="header">
        <div class="logo">
            <img src="{{ url_for('static', filename='src/platform_logo.png') }}" alt="Logo" style="height: 4vh;">
        </div>
    </header>

    <!-- Main content -->
    <div class="content">
        {% block content %}default content{% endblock %}
    </div>

    <!-- Bottom Navigation Bar -->
    <nav class="navbar_1">
        {% if is_admin %}
            <a href="{{ url_for('views.dashboard_page') }}" class="nav-item {% if request.endpoint == 'views.dashboard_page' %}active{% endif %}">
                <ion-icon name="bar-chart-outline" class="nav__icon"></ion-icon>
                <span class="span">Dashboard</span>
            </a>
            <a href="{{ url_for('auth.logout') }}" class="nav-item {% if request.endpoint == 'auth.logout' %}active{% endif %}">
                <ion-icon name="log-out-outline" class="nav__icon"></ion-icon>
                <span class="span">Logout</span>
            </a>
        {% else %}
            <a href="{{ url_for('views.home') }}" class="nav-item {% if request.endpoint == 'views.home' %}active{% endif %}">
                <ion-icon name="home-outline" class="nav__icon"></ion-icon>
                <span class="span">Home</span>
            </a>
            <a href="{{ url_for('views.account') }}" class="nav-item {% if request.endpoint == 'views.account' %}active{% endif %}">
                <ion-icon name="person-circle-outline" class="nav__icon"></ion-icon>
                <span class="span">Account</span>
            </a>
            <a href="{{ url_for('auth.logout') }}" class="nav-item {% if request.endpoint == 'auth.logout' %}active{% endif %}">
                <ion-icon name="log-out-outline" class="nav__icon"></ion-icon>
                <span class="span">Logout</span>
            </a>
        {% endif %}
    </nav>

    <!-- Footer -->
    <footer>
        <p>2024 @ made by 방해금지모드</p>
    </footer>

    {% block scripts %}{% endblock %}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const navbar = document.querySelector('.navbar_1');
            const navItems = document.querySelectorAll('.nav-item');

            navItems.forEach(item => {
                item.addEventListener('mouseenter', () => {
                    navbar.classList.add('expanded');
                });

                item.addEventListener('mouseleave', () => {
                    navbar.classList.remove('expanded');
                });
            });
        });
    </script>
    <script src="{{ url_for('static', filename='js/fcm.js') }}"></script>
</body>
</html>

templates/layouts/layout_routine.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}SmartPlatform Header with Mobile Navigation Bar{% endblock %}</title>

    <!-- 부트스트랩 CSS 링크 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            background-color: #131419;
            color: #fff;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
            width: 100%; 
        }

        .header {
            width: 100%;
            background-color: #131419;
            padding: 20px;
            box-shadow: -5px -5px 10px rgba(255, 255, 255, 0.05), 5px 5px 15px rgba(0, 0, 0, 0.5);
            position: fixed;
            top: 0;
            left: 0;
            text-align: center;
            z-index: 1000;
        }

        .content {
            margin-top: 85px;
            padding-bottom: 60px;
            height: 800px;
            width: 100%; /* 변경: 360px에서 100%로 */
            max-width: 360px; /* 추가: 최대 너비 설정 */
            display: flex; /* 추가: flexbox 사용 */
            flex-direction: column; /* 추가: 세로 방향 정렬 */
            align-items: center; /* 추가: 가로 중앙 정렬 */
        }

        .navbar {
            position: fixed;
            bottom: 0;
            left: 0; /* 추가: 왼쪽 정렬 확실히 하기 */
            width: 100%;
            background-color: #131419;
            display: flex;
            justify-content: space-around;
            align-items: center;
            height: 60px;
            box-shadow: -5px -5px 10px rgba(255, 255, 255, 0.05), 5px 5px 15px rgba(0, 0, 0, 0.5);
            z-index: 1000;
        }
        .nav-item {
            text-decoration: none;
            color: #fff;
            font-size: 16px;
            text-transform: uppercase;
            transition: color 0.3s ease;
            padding: 10px; /* 각 아이템의 내부 여백 */
        }

        .nav-item:hover {
            color: #96C9F4;
        }

        .nav-item svg {
            margin-top: 4px; /* SVG 아이콘과 텍스트 사이의 간격 조정 */
        }
    </style>
    {% block styles %}{% endblock %}
</head>
<body>
    <!-- Header -->
    <header class="header">
        <div class="logo">
            <img src="{{ url_for('static', filename='src/routine-logo.png') }}" alt="Logo" style="height: 6vh;">
        </div>
    </header>

    <!-- Main content -->
    <div class="content">
        {% block content %}default content{% endblock %}
    </div>

    <!-- Bottom Navigation Bar -->
    <nav class="navbar">
        <a href="{{ url_for('views.routine') }}" class="nav-item" >
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-house-door" viewBox="0 0 16 16">
                <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4z"/>
            </svg>
        </a>
        <a href="{{ url_for('views.routine') }}" class="nav-item">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
            </svg>
        </a>
        <a href="{{ url_for('views.control_home') }}" class="nav-item">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-clipboard-data" viewBox="0 0 16 16">
                <path d="M4 11a1 1 0 1 1 2 0v1a1 1 0 1 1-2 0zm6-4a1 1 0 1 1 2 0v5a1 1 0 1 1-2 0zM7 9a1 1 0 0 1 2 0v3a1 1 0 1 1-2 0z"/>
                <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1z"/>
                <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0z"/>
            </svg>
        </a>
        <!-- <a href="{{ url_for('views.routine') }}" class="nav-item">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-gear-wide-connected" viewBox="0 0 16 16">
                <path d="M7.068.727c.243-.97 1.62-.97 1.864 0l.071.286a.96.96 0 0 0 1.622.434l.205-.211c.695-.719 1.888-.03 1.613.931l-.08.284a.96.96 0 0 0 1.187 1.187l.283-.081c.96-.275 1.65.918.931 1.613l-.211.205a.96.96 0 0 0 .434 1.622l.286.071c.97.243.97 1.62 0 1.864l-.286.071a.96.96 0 0 0-.434 1.622l.211.205c.719.695.03 1.888-.931 1.613l-.284-.08a.96.96 0 0 0-1.187 1.186l.081.283c.275.96-.918 1.65-1.613.931l-.205-.211a.96.96 0 0 0-1.622.434l-.071.286c-.243.97-1.62.97-1.864 0l-.071-.286a.96.96 0 0 0-1.622-.434l-.205.211c-.695.719-1.888.03-1.613-.931l.08-.284a.96.96 0 0 0-1.186-1.187l-.284.081c-.96.275-1.65-.918-.931-1.613l.211-.205a.96.96 0 0 0-.434-1.622l-.286-.071c-.97-.243-.97-1.62 0-1.864l.286-.071a.96.96 0 0 0 .434-1.622l-.211-.205c-.719-.695-.03-1.888.931-1.613l.284.08a.96.96 0 0 0 1.187-1.186l-.081-.284c-.275-.96.918-1.65 1.613-.931l.205.211a.96.96 0 0 0 1.622-.434zM12.973 8.5H8.25l-2.834 3.779A4.998 4.998 0 0 0 12.973 8.5m0-1a4.998 4.998 0 0 0-7.557-3.779l2.834 3.78zM5.048 3.967l-.087.065zm-.431.355A4.98 4.98 0 0 0 3.002 8c0 1.455.622 2.765 1.615 3.678L7.375 8zm.344 7.646.087.065z"/>
            </svg>
        </a> -->
        <a href="{{ url_for('views.home') }}" class="nav-item">
            <img src="{{ url_for('static', filename='src/platform-logo.png') }}" alt="Logo" style="height: 2vh;">
        </a>
    </nav>

    {% block scripts %}{% endblock %}
    <script src="{{ url_for('static', filename='js/fcm.js') }}"></script>
</body>
</html>