main/auth.py
from flask import Blueprint, request, redirect, url_for, render_template, flash, session, jsonify, current_app
import flask_login
import bcrypt
import datetime
from model.model_platform import User, UserProfiles, UserRoles, Roles, Permissions, db, Session
from model.google import init_google_oauth
from config import Config
from .routine_schedule import schedule_notifications

auth = Blueprint('auth', __name__)
google = init_google_oauth(Config.GOOGLE_OAUTH2_CLIENT_ID, Config.GOOGLE_OAUTH2_CLIENT_SECRET)

# 로그인
@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        id = request.form.get("id")
        password = request.form.get("password")
        user = User.query.filter_by(ID=id).first()

        if user and bcrypt.checkpw(password.encode('utf-8'), user.Password.encode('utf-8')):
            flask_login.login_user(user)
            try:
                with current_app.app_context():
                    schedule_notifications()
            except Exception as e:
                print(f"Error scheduling notifications: {e}")

            if user.is_admin():
                return jsonify({"success": True, "redirect": url_for("views.dashboard_page")})
            else:
                return jsonify({"success": True, "redirect": url_for("views.home")})
        else:
            return jsonify({"success": False, "message": "로그인에 실패했습니다. 아이디와 비밀번호를 확인해주세요."})
        
    user_agent = request.user_agent.string
    if "Mobi" in user_agent:
        print('mobile')
        return redirect(url_for("auth.m_login")) 
    else:
        return render_template('Platform/login.html')

@auth.route('/m.login', methods=['GET', 'POST'])
def m_login():
    user_agent = request.user_agent.string
    if "Mobi" in user_agent:
        print('mobile')
        return render_template('Platform/m_login.html')
    else:
        return redirect(url_for("auth.login")) 
    

# 구글 로그인
@auth.route("/google/login")
def google_login():
    return google.authorize(callback=url_for('auth.google_callback', _external=True))

@auth.route('/google/callback')
def google_callback():
    resp = google.authorized_response()
    if resp is None or resp.get('access_token') is None:
        return 'Access denied: reason=%s error=%s' % (
            request.args['error_reason'],
            request.args['error_description']
        )
    
    session['google_token'] = (resp['access_token'], '')
    user_info = google.get('userinfo').data

    email = user_info['email']
    name = user_info.get('name', '')

    session_db = Session()
    user = session_db.query(User).filter_by(Email=email).first()

    if user is None:
        new_user = User(
            ID=email,  
            Username=name,
            Password='', 
            Email=email,
            Phone='',
            DateOfBirth=None,
            DateJoined=datetime.datetime.now(),
            Status='active'
        )
        session_db.add(new_user)
        session_db.commit()

        new_user_profile = UserProfiles(
            UserID=new_user.UserID,
            ID=email,
            Username=name,
            FirstName='새로운',
            LastName='뉴비',
            Address=''
        )
        session_db.add(new_user_profile)
        session_db.commit()

        default_role = session_db.query(Roles).filter_by(RoleName='Basic User').first()
        default_permission = session_db.query(Permissions).filter_by(PermissionName='User').first()

        new_user_role = UserRoles(
            UserID=new_user.UserID,
            RoleID=default_role.RoleID,
            PermissionID=default_permission.PermissionID
        )
        session_db.add(new_user_role)
        session_db.commit()

        user = new_user

    flask_login.login_user(user)
    return redirect(url_for('views.home'))

@google.tokengetter
def get_google_oauth_token():
    return session.get('google_token')

def remove_fcm_token():
    user_id = flask_login.current_user.UserID
    user = User.query.get(user_id)
    if user:
        user.FCMToken = None
        db.session.commit()
        return jsonify({"message": "Token removed successfully"}), 200
    return jsonify({"error": "User not found"}), 404
# 로그아웃
@auth.route("/logout")
def logout():
    remove_fcm_token()
    flask_login.logout_user()
    return redirect(url_for('auth.login'))

# 회원가입
@auth.route('/register', methods=['POST'])
def register():
    name = request.form.get('name')
    join_id = request.form.get('join_id')
    join_pwd = request.form.get('join_pwd')
    # birth = request.form.get('birth')
    phone = request.form.get('phone')
    email = request.form.get('email')
    # address = request.form.get('address')
    # address2 = request.form.get('address2')
    # address3 = request.form.get('address3')

    print(f"join_id: {join_id}")
    hashed_pwd = bcrypt.hashpw(join_pwd.encode('utf-8'), bcrypt.gensalt())
    # full_address = f"{address}, {address2}, {address3}"
    
    session_db = Session()
    
    new_user = User(
        ID=join_id,
        Username=name,
        Password=hashed_pwd,
        Email=email,
        Phone=phone,
        # DateOfBirth=birth,
        DateJoined= datetime.datetime.now(),
        Status='active'
    )
    session_db.add(new_user)
    session_db.commit()

    new_user_profile = UserProfiles(
        UserID=new_user.UserID, 
        ID=join_id, 
        Username=name,
        FirstName="새로운",
        LastName="뉴비",
        # Address=full_address
    )
    db.session.add(new_user_profile)
    db.session.commit()

    default_role = session_db.query(Roles).filter_by(RoleName='Basic User').first()
    default_permission = session_db.query(Permissions).filter_by(PermissionName='User').first()

    new_user_role = UserRoles(
        UserID=new_user.UserID,
        RoleID=default_role.RoleID,
        PermissionID=default_permission.PermissionID
    )
    session_db.add(new_user_role)
    session_db.commit()
    session_db.close()

    flash('Account created successfully!', 'success')
    return redirect(url_for('auth.login'))

# 아이디 중복 확인
@auth.route('/check_id', methods=['GET'])
def check_id():
    join_id = request.args.get('join_id')
    user = User.query.filter_by(ID=join_id).first()
    return jsonify({'exists': user is not None})

# 개인정보 동의 문서 읽어오기
@auth.route('/get_terms_of_use')
def get_terms_of_use():
    with open('static/src/TermsofUse/TermsofUse.txt', 'r', encoding='utf-8') as file:
        terms_of_use = file.read()
    return terms_of_use

@auth.route('/get_personal_information')
def get_personal_information():
    with open('static/src/TermsofUse/PersonalInformation.txt', 'r', encoding='utf-8') as file:
        personal_information = file.read()
    return personal_information

templates/Platform/dashboard.html
{% extends 'layouts/layout.html' %}

{% block title %}관리자 대시보드{% endblock %}
<!-- 내용 추가 -->
{% block content %}
<main>
    <section id="graph-container">
        <div class="graph-item">
            <h2>서비스별 구독자 추이</h2>
            <div class="controls">
                <div>
                    <label for="serviceSelect">서비스 선택:</label>
                    <select id="serviceSelect"></select>
                    <select id="daysSelect">
                        <option value="7">7일</option>
                        <option value="30" selected>30일</option>
                        <option value="90">90일</option>
                    </select>
                </div>
                <div>
                    <label for="startDate">시작일:</label>
                    <input type="date" id="startDate">
                    <label for="endDate">종료일:</label>
                    <input type="date" id="endDate">
                </div>
                <button id="updateChart">차트 업데이트</button>
            </div>
            <canvas id="subscriptionTrendChart"></canvas>
        </div>


        <div class="graph-item">
            <h2>일일 활성 사용자</h2>
            <canvas id="active-users-graph"></canvas>
        </div>

        <div class="graph-item">
            <h2>일일 서비스 사용량</h2>
            <canvas id="service-usage-graph"></canvas>
        </div>

        <div class="graph-item">
            <h2>연령대별 사용자 분포</h2>
            <canvas id="ageDistributionChart"></canvas>
        </div>
    </section>
</main>
{% endblock %}


<!-- 추가 CSS 예시 -->
{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/Platform/dashboard.css') }}">
{% endblock %}

<!-- 추가 JavaScript 예시 -->
{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{{ url_for('static', filename='js/Platform/dashboard.js') }}"></script>
{% endblock %}

templates/Platform/donotdisturb.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>방해금지모드를 소개합니다</title>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        body {
            font-family: 'Noto Sans KR', sans-serif;
            background-color: #000000;
            color: #F2DF7E;
            margin: 0;
            padding: 0;
        }

        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(-20px); }
            to { opacity: 1; transform: translateY(0); }
        }

        .header {
            background: linear-gradient(to bottom, #F2DF7E, #000000);
            color: #FFFFFF;
            text-align: center;
            padding: 2rem;
        }
        .header h1, .header p {
            text-shadow: 2px 2px 4px rgba(0,0,0,0.5);
        }
        .container {
            display: grid;
            grid-template-columns: 1fr;
            gap: 2rem;
            padding: 2rem;
            max-width: 800px;
            margin: 0 auto;
        }
        .content-div {
            background-color: #FFFFFF;
            border-radius: 10px;
            padding: 2rem;
            box-shadow: inset -2px -2px 6px rgba(255, 255, 255, 0.05), inset 2px 2px 6px rgba(0, 0, 0, 0.8);
            color: #000000;
            text-align: center;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .content-div p {
            max-width: 90%;
            line-height: 1.6;
        }
        .content-div:nth-child(1) {
            animation: fadeIn 0.5s ease-in forwards;
        }
        .content-div:nth-child(2) {
            animation: fadeIn 0.5s ease-in forwards;
            animation-delay: 0.1s;
        }
        .content-div:nth-child(3) {
            animation: fadeIn 0.5s ease-in forwards;
            animation-delay: 0.2s;
        }
        .h2-container {
            background-color: #FFFFFF;
            padding: 10px 20px;
            border-radius: 5px;
            box-shadow: 0 10px 6px -7px rgba(0, 0, 0, 0.5);
            display: inline-block;
            margin-bottom: 20px;
        }
        h2 {
            color: #F28B30;
            text-align: center;
            font-size: 2em;
            margin: 0;
        }
        .team-name {
            display: flex;
            align-items: center;
            justify-content: center;
        }
        .team-name i {
            margin-left: 10px;
            font-size: 1.8em;
            color:#F2B035;
        }
        .important-word {
            font-size: 1.5em;
            font-weight: 700;
            color: #000000;
            margin: 1rem 0 0.5rem; /* 상단 마진은 그대로, 하단 마진을 줄임 */
            text-transform: uppercase;
            letter-spacing: 2px;
            position: relative;
            display: inline-block;
        }

        .content-div p {
            max-width: 90%;
            line-height: 1.6;
            margin-top: 0.5rem; /* p 태그의 상단 마진을 줄임 */
        }
        .important-word::after {
            content: '';
            position: absolute;
            left: 0;
            bottom: -5px;
            width: 100%;
            height: 3px;
            background-color: #F28B30;
            transform: scaleX(0);
            transition: transform 0.3s ease-in-out;
        }
        .important-word:hover::after {
            transform: scaleX(1);
        }

        /* 홈 돌아가기 버튼 */
        .btn-container {
            text-align: center;
            margin-top: 2rem;
            animation: fadeIn 0.5s ease-in forwards;
            animation-delay: 0.3s;
        }

        .btn {
            display: inline-block;
            padding: 10px 20px;
            background-color: #F28B30;
            color: #FFFFFF;
            text-decoration: none;
            border-radius: 5px;
            font-weight: 700;
            transition: background-color 0.3s, transform 0.3s;
            margin: 50px;
        }

        .btn:hover {
            background-color: #F2B035;
            transform: scale(1.05);
        }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="team-name">TEAM <i class="fas fa-moon"></i> 방해금지모드 </h1>
        <p>일과 삶의 경계를 바로잡고, 삶을 주도적으로 살아가다</p>
    </div>
    <div class="container">
        <div class="content-div">
            <div class="h2-container">
                <h2>VISION</h2>
            </div>
            <p class="important-word">자립</p>
            <p>누군가가 우리의 가치를 정해주는 것이 아닌 스스로 가치를 결정합니다.</p>
        </div>
        <div class="content-div">
            <div class="h2-container">
                <h2>MISSION</h2>
            </div>
            <p class="important-word"> 삶을 주도적으로 </p>
            <p>우리는 일상 자동화를 원하지만, 시스템의 지배를 원하는 것은 아닙니다. <br>
            사용자가 삶을 자기주도적으로 살아갈 수 있도록 돕습니다.</p>
        </div>
        <div class="content-div">
            <div class="h2-container">
                <h2>HOW TO WORK?</h2>
            </div>
            <p class="important-word">즐겁게 Entertain</p>
            <p>우리는 생산자 Productor 이자 사용자 User 입니다. <br>
            우리가 즐겁게 일하는 것이 사용자를 즐겁게 하는 일입니다.</p>
            <p class="important-word">효율적으로 Efficiently</p>
            <p>우리는 일 work 과 삶 life 의 경계를 중요하게 여깁니다. <br>
            메모하고, 공유하고, 개선하여 문제를 효율적으로 해결합니다.</p>
            <p class="important-word">기초부터 Basic</p>
            <p>실수는 무지와 자만에서 나옵니다. <br>
            우리는 문제의 원인을 기초에서부터 찾아보고, 함께 공부해 나갑니다.</p>
        </div>
    </div>
    <div class="btn-container">
        <a href="{{url_for('views.home')}}" class="btn">홈으로 돌아가기</a>
    </div>
</body>
</html>

templates/Platform/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Platform Login</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/Platform/login.css') }}">
</head>
<body>
<div class="wrapper">
  <div class="logo">
    <img src="{{ url_for('static', filename='src/platform_logo.png') }}" alt="Logo" class="logo-image" style="height: 10vw;">
  </div>
  
  <div class="container">
    <div class="sign-up-container">
      <form method="POST" action="/auth/register">
        <h1>Create Account</h1>
        <div class="social-links">
          <div>
            <a hre="{{url_for('auth.google_login')}}"><i class="fa fa-google" aria-hidden="true"></i></a>
          </div>
        </div>
        <span>or use your email for registration</span>
        <input type="text" name="name" placeholder="Name">
        <div class="input-container">
          <input type="text" name="join_id" id="join_id" placeholder="ID(특수문자 X, 6자 이상)" style="width: 100%;">
          <button type="button" id="checkIdBtn">중복확인</button>
        </div>
        <span class="material-icons icon" id="idCheckIcon"></span>
        <div id="idFeedback" class="feedback"></div>
        <input type="password" name="join_pwd" id="join_pwd" placeholder="PWD(8~20자, 문자/숫자/특수문자)">
        <div id="pwdFeedback" class="feedback"></div>
        <input type="date" name="birth" min="1900-01-01" id="birthDate" required>
        <input type="tel" name="phone" oninput="hypenTel(this)" maxlength="13" placeholder="Phone">
        <input type="email" name="email" placeholder="email">
        <button class="form_btn">Sign Up</button>
      </form>
    </div>
    <div class="sign-in-container">
      <form method="POST" action="/auth/login">
        <h1>Sign In</h1>
        <div class="social-links">
          <div>
            <a href="{{ url_for('auth.google_login')}}"><i class="fa fa-google" aria-hidden="true"></i></a>
          </div>
        </div>
        <span>or use your account</span>
        <input type="text" placeholder="ID" name="id" />
        <input type="password" placeholder="Password" name="password" />
        <button class="form_btn">Sign In</button>
      </form>
    </div>
    <div class="overlay-container">
      <div class="overlay-left">
        <h1>Welcome!</h1>
        <p>To keep connected with us please login with your personal info</p>
        <button id="signIn" class="overlay_btn">Sign In</button>
      </div>
      <div class="overlay-right">
        <h1>Hello, Friend</h1>
        <p>Enter your personal details and start journey with us</p>
        <button id="signUp" class="btn-open-modal">Sign Up</button>
        <!-- <button id="signUp" class="overlay_btn">Sign Up</button> -->
      </div>
    </div>
  </div>
</div>

<!-- 개인정보동의 모달 -->
<div class="modal" id="termsOfUseModal">
  <div class="modal_body">
      <h2>이용약관</h2>
      <div class="modal_content">
        <pre id="termsOfUseContent">내용을 불러오는 중...</pre>
      </div>

      <h2>개인정보 처리방침</h2>
      <div class="modal_content">
        <pre id="personalInformationContent">내용을 불러오는 중...</pre>
      </div>
      
      <div>
        <button type="button" class="submit_modal"> 전체 동의</button>
        <button type="button" class="close_modal">취소</button>
      </div>
  </div>
</div>
<script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-messaging.js"></script>
<script src="{{ url_for('static', filename='js/fcm.js') }}"></script>
<script src="{{ url_for('static', filename='js/Platform/login.js') }}"></script>
</body>
</html>

templates/Platform/m_login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Platform Login</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/Platform/m_login.css') }}">
    <script src="../../static/js/Platform/m_login.js"></script>
</head>

<body>
    <div class="form-container">
        <div class="logo">
            <img src="{{ url_for('static', filename='src/platform_logo.png') }}" alt="Logo" class="logo-image" style="height: 10vw;">
        </div>

        <!-- Login Form -->
        <form class="form login-form" method="POST" action="/auth/login">

            <div class="flex-column">
                <label for="id">ID </label>
            </div>
            <div class="inputForm">
                <svg height="20" viewBox="0 0 32 32" width="20" xmlns="http://www.w3.org/2000/svg">
                    <g id="Layer_3" data-name="Layer 3">
                        <path
                            d="m30.853 13.87a15 15 0 0 0 -29.729 4.082 15.1 15.1 0 0 0 12.876 12.918 15.6 15.6 0 0 0 2.016.13 14.85 14.85 0 0 0 7.715-2.145 1 1 0 1 0 -1.031-1.711 13.007 13.007 0 1 1 5.458-6.529 2.149 2.149 0 0 1 -4.158-.759v-10.856a1 1 0 0 0 -2 0v1.726a8 8 0 1 0 .2 10.325 4.135 4.135 0 0 0 7.83.274 15.2 15.2 0 0 0 .823-7.455zm-14.853 8.13a6 6 0 1 1 6-6 6.006 6.006 0 0 1 -6 6z">
                        </path>
                    </g>
                </svg>
                <input type="text" class="input" name="id" id="id" placeholder="Enter your ID" required>
            </div>

            <div class="flex-column">
                <label for="password">Password </label>
            </div>
            <div class="inputForm">
                <svg height="20" viewBox="-64 0 512 512" width="20" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="m336 512h-288c-26.453125 0-48-21.523438-48-48v-224c0-26.476562 21.546875-48 48-48h288c26.453125 0 48 21.523438 48 48v224c0 26.476562-21.546875 48-48 48zm-288-288c-8.8125 0-16 7.167969-16 16v224c0 8.832031 7.1875 16 16 16h288c8.8125 0 16-7.167969 16-16v-224c0-8.832031-7.1875-16-16-16zm0 0">
                    </path>
                    <path
                        d="m304 224c-8.832031 0-16-7.167969-16-16v-80c0-52.929688-43.070312-96-96-96s-96 43.070312-96 96v80c0 8.832031-7.167969 16-16 16s-16-7.167969-16-16v-80c0-70.59375 57.40625-128 128-128s128 57.40625 128 128v80c0 8.832031-7.167969 16-16 16zm0 0">
                    </path>
                </svg>
                <input type="password" class="input" name="password" id="password" placeholder="Enter your Password" required>
                <svg viewBox="0 0 576 512" height="1em" xmlns="http://www.w3.org/1999/xlink">
                    <path
                        d="M288 32c-80.8 0-145.5 36.8-192.6 80.6C48.6 156 17.3 208 2.5 243.7c-3.3 7.9-3.3 16.7 0 24.6C17.3 304 48.6 356 95.4 399.4C142.5 443.2 207.2 480 288 480s145.5-36.8 192.6-80.6c46.8-43.5 78.1-95.4 93-131.1c3.3-7.9 3.3-16.7 0-24.6c-14.9-35.7-46.2-87.7-93-131.1C433.5 68.8 368.8 32 288 32zM144 256a144 144 0 1 1 288 0 144 144 0 1 1 -288 0zm144-64c0 35.3-28.7 64-64 64c-7.1 0-13.9-1.2-20.3-3.3c-5.5-1.8-11.9 1.6-11.7 7.4c.3 6.9 1.3 13.8 3.2 20.7c13.7 51.2 66.4 81.6 117.6 67.9s81.6-66.4 67.9-117.6c-11.1-41.5-47.8-69.4-88.6-71.1c-5.8-.2-9.2 6.1-7.4 11.7c2.1 6.4 3.3 13.2 3.3 20.3z">
                    </path>
                </svg>
            </div>

            <div class="flex-row">
                <div>
                    <input type="checkbox">
                    <label>Remember me </label>
                </div>
                <span class="span">Forgot password?</span>
            </div>
            <button class="button-submit" type="submit">Sign In</button>
            <p class="p">Don't have an account?<span class="span" id="show-register">Sign Up</span></p>
            <p class="p line">Or With</p>

            <div class="flex-row">
                <button class="btn google" type="button" onclick="redirectToGoogleLogin()">
                        <svg version="1.1" width="20" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                        xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 512 512"
                                style="enable-background:new 0 0 512 512;" xml:space="preserve">
                                <path style="fill:#FBBB00;" d="M113.47,309.408L95.648,375.94l-65.139,1.378C11.042,341.211,0,299.9,0,256
                        c0-42.451,10.324-82.483,28.624-117.732h0.014l57.992,10.632l25.404,57.644c-5.317,15.501-8.215,32.141-8.215,49.456
                        C103.821,274.792,107.225,292.797,113.47,309.408z"></path>
                                <path style="fill:#518EF8;" d="M507.527,208.176C510.467,223.662,512,239.655,512,256c0,18.328-1.927,36.206-5.598,53.451
                        c-12.462,58.683-45.025,109.925-90.134,146.187l-0.014-0.014l-73.044-3.727l-10.338-64.535
                        c29.932-17.554,53.324-45.025,65.646-77.911h-136.89V208.176h138.887L507.527,208.176L507.527,208.176z"></path>
                                <path style="fill:#28B446;" d="M416.253,455.624l0.014,0.014C372.396,490.901,316.666,512,256,512
                        c-97.491,0-182.252-54.491-225.491-134.681l82.961-67.91c21.619,57.698,77.278,98.771,142.53,98.771
                        c28.047,0,54.323-7.582,76.87-20.818L416.253,455.624z"></path>
                                <path style="fill:#F14336;" d="M419.404,58.936l-82.933,67.896c-23.335-14.586-50.919-23.012-80.471-23.012
                        c-66.729,0-123.429,42.957-143.965,102.724l-83.397-68.276h-0.014C71.23,56.123,157.06,0,256,0
                        C318.115,0,375.068,22.126,419.404,58.936z"></path>
                        </svg>Google
                </button>
            </div>
        </form>
        
        <!-- Registration Form -->
        <form class="form register-form" method="POST" action="/auth/register" style="display: none;">
            <p class="title">Register </p>
            <p class="message">Signup now and get full access to our app. </p>
            <label>
                <input class="input" type="text" name="name" placeholder="" required>
                <span>Name</span>
            </label>
            
            <label class="input-with-button">
                <input class="input" type="text" name="join_id" placeholder="" id="register-id-input" required>
                <button type="button" class="check-id-btn">중복확인</button>
                <span>ID(특수문자X, 6자 이상)</span>
            </label>
            
            <label>
                <input class="input" type="password" name="join_pwd" placeholder="" required id="join_pwd">
                <span class="pwd-span">Password(8~20자, 숫자/문자/특수문자)</span>
            </label>
            <label>
                <input class="input" type="password" placeholder="" required id="confirm_pwd">
                <span class="confirm-pwd-span">Confirm password</span>
            </label>
            
            <label>
                <input class="input" type="date" name="birth" placeholder="" required>
                <span>Birth</span>
            </label>
            
            <label>
                <input class="input" type="tel" name="phone" placeholder="" required>
                <span>Phone</span>
            </label>
            
            <label>
                <input class="input" type="email" name="email" placeholder="" required>
                <span>Email</span>
            </label>
            
            <button class="submit" type="submit">Submit</button>
            <p class="signin">Already have an account? <a href="#" id="show-login">Sign In</a></p>
        </form>
    </div>

    <!-- 개인정보동의 모달 -->
    <div class="modal" id="termsOfUseModal">
        <div class="modal_body">
            <h2>이용약관</h2>
            <div class="modal_content">
            <pre id="termsOfUseContent">내용을 불러오는 중...</pre>
            </div>
    
            <h2>개인정보 처리방침</h2>
            <div class="modal_content">
            <pre id="personalInformationContent">내용을 불러오는 중...</pre>
            </div>
            
            <div>
            <button type="button" class="submit_modal"> 전체 동의</button>
            <button type="button" class="close_modal">취소</button>
            </div>
        </div>
    </div>

    <script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-messaging.js"></script>
    <script src="{{ url_for('static', filename='js/fcm.js') }}"></script>
    <script src="{{ url_for('static', filename='js/Platform/m_login.js') }}"></script>
    <script>
        function redirectToGoogleLogin() {
            window.location.href = "{{ url_for('auth.google_login') }}";
        }
    </script>
</body>

</html>